fixtures:
  repositories:
    stdlib: 
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "4.6.0"
    apache: 
      repo: "https://github.com/puppetlabs/puppetlabs-apache.git"
      ref:  "1.10.0"  
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
      ref:  "1.1.2"
  symlinks:
    wrap_frontend: "#{source_dir}"
